export default {
  loginDetails: {
    email: "",
    password: "",
  },
  signupVendor: {
    first_name: "",
    last_name: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone_number: "",
    address: {
      street: "",
      lga: "",
      state: "",
    },
    business_name: "",
  },
  signupRider: {
    first_name: "",
    last_name: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone_number: "",
    address: {
      street: "",
      lga: "",
      state: "",
    },
    company_name: "",
  },
  signupCustomer: {
    first_name: "",
    last_name: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone_number: "",
    address: {
      street: "",
      lga: "",
      state: "",
    },
  },
  formValidation: {
    first_name: false,
    last_name: false,
    email: false,
    password: false,
    phone_number: false,
    address: {
      street: false,
      lga: false,
      state: false,
    },
    business_name: false,
    company_name: false,
    confirmPassword: false,
  },
};
